Repository Kicchu02/States, pull requests merged in 2024-08, with the labels that each got.

#1 Initial Project Setup
  .tool-versions
  App.tsx
  README.md
  components/WelcomePage.tsx
  types/States.ts
Labels: documentation

#2 Fix Initial Setup
  .tool-versions
  README.md
  components/WelcomePage.tsx
Labels: documentation

#4 Add Prettier And Eslint Configuration
  .eslintrc.json
  .prettierrc.json
  components/ClickCorrectStatePage.tsx
  components/EnterCorrectStateNamePage.tsx
  components/StateMultipleChoiceQuizPage.tsx
  package-lock.json
  package.json
Labels: good first issue

#7 Design WelcomePage
  App.tsx
  Styles.tsx
  components/WelcomePage.tsx
  types/States.tsx
  types/Themes.tsx
  ui-components/StyledButton.tsx
Labels: enhancement
